[package]
name = "anscombe"
version = "0.1.0"
edition = "2021"

[dependencies]
cursive = "0.21.1"
itertools = "0.13.0"
ndarray = "0.16.1"
rand = "0.8.5"
image = "0.24"

[profile.dev]
debug = "full"

[profile.release]
debug = true